### ISSUE TITLE
0.2.0 missing variable init

### ISSUE THREAD

**Issue by ntoff** [ntoff/OctoPrint-FanSpeedSlider#11]
```2018-12-31 00:53:42,494 - octoprint.util.comm - ERROR - Error while processing hook fanspeedslider for phase queuing and command M110 N0:
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.3.10-py2.7.egg/octoprint/util/comm.py", line 3085, in _process_command_phase
    hook_results = hook(self, phase, command, command_type, gcode, subcode=subcode, tags=tags)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_fanspeedslider/__init__.py", line 111, in rewrite_m106
    elif self.lockfan and gcode and gcode.startswith(('M106', 'M107')):
AttributeError: 'FanSliderPlugin' object has no attribute 'lockfan'
```

Who's an idiot who forgot to initialise the variable before using it? who's a big fat idiot? yes I am. "master" branch has the fix

**Comment by ntoff** [comment]
fixed in 0.2.1 innit
